version: "3.9"

services:
  # Main database for subscriber, billing, user data
  postgres:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: mvno
      POSTGRES_PASSWORD: mvno_dev_password
      POSTGRES_DB: mvno_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mvno -d mvno_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Event streaming for microservices communication
  kafka:
    image: redpandadata/redpanda:v24.3.1
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --kafka-addr=PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://kafka:29092,OUTSIDE://localhost:9092
    ports:
      - "9092:9092"
      - "9644:9644"
    healthcheck:
      test: ["CMD-SHELL", "rpk cluster info"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Vector database for AI knowledge base (using pgvector extension)
  vector-db:
    image: ankane/pgvector
    restart: unless-stopped
    environment:
      POSTGRES_USER: vector
      POSTGRES_PASSWORD: vector_dev_password
      POSTGRES_DB: vector_db
    ports:
      - "5433:5432"
    volumes:
      - vectordata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vector -d vector_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Database administration GUI
  pgadmin:
    image: dpage/pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@wingtel.dev
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "8080:80"
    depends_on:
      postgres:
        condition: service_healthy
      vector-db:
        condition: service_healthy

  # Redis for caching and session storage
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API Gateway (NestJS)
  api-gateway:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://mvno:mvno_dev_password@postgres:5432/mvno_db
      - REDIS_URL=redis://redis:6379
      - KAFKA_BROKERS=kafka:29092
      - VECTOR_DB_URL=postgresql://vector:vector_dev_password@vector-db:5432/vector_db
      - SUPABASE_URL=${SUPABASE_URL:-}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY:-}
      - JWT_SECRET=${JWT_SECRET:-development-secret-key}
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    restart: unless-stopped

  # AI Services (Python FastAPI)
  ai-services:
    build:
      context: ./ai-services
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://mvno:mvno_dev_password@postgres:5432/mvno_db
      - VECTOR_DB_URL=postgresql://vector:vector_dev_password@vector-db:5432/vector_db
      - REDIS_URL=redis://redis:6379
      - OPENAI_API_KEY=${OPENAI_API_KEY:-}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
      - SUPABASE_URL=${SUPABASE_URL:-}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY:-}
    volumes:
      - ./ai-services:/app
      - /app/__pycache__
    depends_on:
      postgres:
        condition: service_healthy
      vector-db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped

  # Frontend (React)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
      - REACT_APP_AI_SERVICES_URL=http://localhost:8000
      - REACT_APP_SUPABASE_URL=${SUPABASE_URL:-}
      - REACT_APP_SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY:-}
      - REACT_APP_ENVIRONMENT=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - api-gateway
    restart: unless-stopped

  # Background job processor
  worker:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://mvno:mvno_dev_password@postgres:5432/mvno_db
      - REDIS_URL=redis://redis:6379
      - KAFKA_BROKERS=kafka:29092
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_healthy
    restart: unless-stopped

volumes:
  pgdata:
  vectordata:
  redisdata:

networks:
  default:
    name: wingtel-network 