# Netlify Configuration for Wingtel AI + BeQuick Enhanced Platform
# Modern React SPA deployment with AI services integration

[build]
  # Build command for the React frontend
  command = "cd frontend && npm run build"
  
  # Directory where the built frontend files will be
  publish = "frontend/dist"
  
  # Install dependencies
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF frontend/"

[build.environment]
  # Node.js version for builds
  NODE_VERSION = "18"
  
  # Enable modern build features
  NODE_ENV = "production"
  GENERATE_SOURCEMAP = "false"
  
  # Build optimizations
  CI = "true"
  DISABLE_ESLINT_PLUGIN = "true"

# SPA routing - redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# AI Services proxy (you'll need to update this with your deployed AI service URL)
[[redirects]]
  from = "/api/*"
  to = "https://wingtel-ai-services.herokuapp.com/:splat"
  status = 200
  force = false
  headers = {X-From = "Netlify"}

# Health check endpoint (removed - not needed for frontend)

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # HTTPS and security
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    
    # CORS for API calls
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    
    # Content Security Policy for BeQuick-style dashboard
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: https:; connect-src 'self' https://*.herokuapp.com https://api.openai.com"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment-specific settings
[context.production]
  command = "cd frontend && npm run build"
  [context.production.environment]
    NODE_ENV = "production"
    VITE_API_URL = "https://wingtel-ai-services.herokuapp.com"
    VITE_ENVIRONMENT = "production"

[context.deploy-preview]
  command = "cd frontend && npm run build"
  [context.deploy-preview.environment]
    NODE_ENV = "development"
    VITE_API_URL = "https://wingtel-ai-services-dev.herokuapp.com"
    VITE_ENVIRONMENT = "preview"

# Functions configuration (for any serverless functions)
[functions]
  directory = "packages/frontend/netlify/functions"
  node_bundler = "esbuild"

# Form handling (if using Netlify forms)
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true

# Split testing (A/B testing)
[[split_tests]]
  path = "/dashboard/*"
  branches = [
    {branch = "main", percentage = 90},
    {branch = "new-ui", percentage = 10}
  ] 